<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('new_form_tidak_langsungs', function (Blueprint $table) {
            $table->id();
            $table->foreignId('works_id')->constrained('work_orders')->onDelete('cascade')->onUpdate('cascade');
            $table->string('nama_saksi')->nullable();
            $table->string('alamat_saksi')->nullable();
            $table->string('nomor_identitas')->nullable();
            $table->string('pekerjaan')->nullable();
            $table->string('no_telpon_saksi')->nullable();
            $table->string('file_nomor_identitas')->nullable();
            $table->string('data_tegangan_tersambung')->nullable();
            $table->string('data_jenis_pengukuran')->nullable();
            $table->string('data_tempat_kedudukan')->nullable();
            $table->string('pembatas_jenis')->nullable();
            $table->string('pembatas_merk')->nullable();
            $table->string('pembatas_rating_arus')->nullable();
            $table->string('pembatas_foto_pembatas')->nullable();
            $table->string('kwh_merk')->nullable();
            $table->string('kwh_no_reg')->nullable();
            $table->string('kwh_no_seri')->nullable();
            $table->string('kwh_tahun')->nullable();
            $table->string('kwh_konstanta')->nullable();
            $table->string('kwh_class')->nullable();
            $table->string('kwh_rating_arus')->nullable();
            $table->string('kwh_tegangan')->nullable();
            $table->string('kwh_lbp')->nullable();
            $table->string('kwh_bp')->nullable();
            $table->string('kwh_total')->nullable();
            $table->string('kwh_kvarh')->nullable();
            $table->string('kwh_foto')->nullable();
            $table->string('ct_merk')->nullable();
            $table->string('ct_cls')->nullable();
            $table->string('ct_rasio')->nullable();
            $table->string('ct_burden')->nullable();
            $table->string('ct_foto')->nullable();
            $table->string('pt_merk')->nullable();
            $table->string('pt_cls')->nullable();
            $table->string('pt_rasio')->nullable();
            $table->string('pt_burden')->nullable();
            $table->string('pt_foto')->nullable();
            $table->string('kubikel_merk')->nullable();
            $table->string('kubikel_type')->nullable();
            $table->string('kubikel_no_seri')->nullable();
            $table->string('kubikel_tahun')->nullable();
            $table->string('kubikel_foto')->nullable();
            $table->string('box_app_merk')->nullable();
            $table->string('box_app_type')->nullable();
            $table->string('box_app_no_seri')->nullable();
            $table->string('box_app_tahun')->nullable();
            $table->string('box_app_foto')->nullable();
            $table->string('pelindung_kwh_peralatan')->nullable();
            $table->string('pelindung_kwh_segel')->nullable();
            $table->string('pelindung_kwh_nomor_tahun_kode_segel')->nullable();
            $table->string('pelindung_kwh_keterangan')->nullable();
            $table->string('pelindung_kwh_foto_sebelum')->nullable();
            $table->string('pelindung_kwh_post_peralatan')->nullable();
            $table->string('pelindung_kwh_post_segel')->nullable();
            $table->string('pelindung_kwh_post_nomor_tahun_kode_segel')->nullable();
            $table->string('pelindung_kwh_foto_sesudah')->nullable();
            $table->string('pelindung_ct_peralatan')->nullable();
            $table->string('pelindung_ct_segel')->nullable();
            $table->string('pelindung_ct_nomor_tahun_kode_segel')->nullable();
            $table->string('pelindung_ct_keterangan')->nullable();
            $table->string('pelindung_ct_foto_sebelum')->nullable();
            $table->string('pelindung_ct_post_peralatan')->nullable();
            $table->string('pelindung_ct_post_segel')->nullable();
            $table->string('pelindung_ct_post_nomor_tahun_kode_segel')->nullable();
            $table->string('pelindung_ct_foto_sesudah')->nullable();
            $table->string('segel_peralatan')->nullable();
            $table->string('segel_segel')->nullable();
            $table->string('segel_nomor_tahun_kode_segel')->nullable();
            $table->string('segel_keterangan')->nullable();
            $table->string('segel_foto_sebelum')->nullable();
            $table->string('segel_post_peralatan')->nullable();
            $table->string('segel_post_segel')->nullable();
            $table->string('segel_post_nomor_tahun_kode_segel')->nullable();
            $table->string('segel_foto_sesudah')->nullable();
            $table->string('tutup_terminal_peralatan')->nullable();
            $table->string('tutup_terminal_segel')->nullable();
            $table->string('tutup_terminal_nomor_tahun_kode_segel')->nullable();
            $table->string('tutup_terminal_keterangan')->nullable();
            $table->string('tutup_terminal_foto_sebelum')->nullable();
            $table->string('tutup_terminal_post_peralatan')->nullable();
            $table->string('tutup_terminal_post_segel')->nullable();
            $table->string('tutup_terminal_post_nomor_tahun_kode_segel')->nullable();
            $table->string('tutup_terminal_foto_sesudah')->nullable();
            $table->string('amr_peralatan')->nullable();
            $table->string('amr_segel')->nullable();
            $table->string('amr_nomor_tahun_kode_segel')->nullable();
            $table->string('amr_keterangan')->nullable();
            $table->string('amr_foto_sebelum')->nullable();
            $table->string('amr_post_peralatan')->nullable();
            $table->string('amr_post_segel')->nullable();
            $table->string('amr_post_nomor_tahun_kode_segel')->nullable();
            $table->string('amr_foto_sesudah')->nullable();
            $table->string('terminal_vt_peralatan')->nullable();
            $table->string('terminal_vt_segel')->nullable();
            $table->string('terminal_vt_nomor_tahun_kode_segel')->nullable();
            $table->string('terminal_vt_keterangan')->nullable();
            $table->string('terminal_vt_foto_sebelum')->nullable();
            $table->string('terminal_vt_post_peralatan')->nullable();
            $table->string('terminal_vt_post_segel')->nullable();
            $table->string('terminal_vt_post_nomor_tahun_kode_segel')->nullable();
            $table->string('terminal_vt_foto_sesudah')->nullable();
            $table->string('terminal_ct_peralatan')->nullable();
            $table->string('terminal_ct_segel')->nullable();
            $table->string('terminal_ct_nomor_tahun_kode_segel')->nullable();
            $table->string('terminal_ct_keterangan')->nullable();
            $table->string('terminal_ct_foto_sebelum')->nullable();
            $table->string('terminal_ct_post_peralatan')->nullable();
            $table->string('terminal_ct_post_segel')->nullable();
            $table->string('terminal_ct_post_nomor_tahun_kode_segel')->nullable();
            $table->string('terminal_ct_foto_sesudah')->nullable();
            $table->string('pintu_peralatan')->nullable();
            $table->string('pintu_segel')->nullable();
            $table->string('pintu_nomor_tahun_kode_segel')->nullable();
            $table->string('pintu_keterangan')->nullable();
            $table->string('pintu_foto_sebelum')->nullable();
            $table->string('pintu_post_peralatan')->nullable();
            $table->string('pintu_post_segel')->nullable();
            $table->string('pintu_post_nomor_tahun_kode_segel')->nullable();
            $table->string('pintu_foto_sesudah')->nullable();
            $table->string('pintu_keterangan_all')->nullable();
            $table->string('wiring_terminal1')->nullable();
            $table->string('wiring_terminal2')->nullable();
            $table->string('wiring_terminal3')->nullable();
            $table->string('wiring_terminal4')->nullable();
            $table->string('wiring_terminal5')->nullable();
            $table->string('wiring_terminal6')->nullable();
            $table->string('wiring_terminal7')->nullable();
            $table->string('wiring_terminal8')->nullable();
            $table->string('wiring_terminal9')->nullable();
            $table->string('wiring_terminal11')->nullable();
            $table->string('wiring_grounding')->nullable();
            $table->string('wiring_keterangan')->nullable();
            $table->string('wiring_diagram')->nullable();
            $table->string('wiring_foto')->nullable();
            $table->string('pengukuran_arus_primer_r')->nullable();
            $table->string('pengukuran_arus_primer_s')->nullable();
            $table->string('pengukuran_arus_primer_t')->nullable();
            $table->string('pengukuran_arus_sekunder_r')->nullable();
            $table->string('pengukuran_arus_sekunder_s')->nullable();
            $table->string('pengukuran_arus_sekunder_t')->nullable();
            $table->string('pengukuran_ct_r')->nullable();
            $table->string('pengukuran_ct_s')->nullable();
            $table->string('pengukuran_ct_t')->nullable();
            $table->string('pengukuran_akurasi_r')->nullable();
            $table->string('pengukuran_akurasi_s')->nullable();
            $table->string('pengukuran_akurasi_t')->nullable();
            $table->string('pengukuran_voltase_primer_r')->nullable();
            $table->string('pengukuran_voltase_primer_s')->nullable();
            $table->string('pengukuran_voltase_primer_t')->nullable();
            $table->string('pengukuran_voltase_sekunder_r')->nullable();
            $table->string('pengukuran_voltase_sekunder_s')->nullable();
            $table->string('pengukuran_voltase_sekunder_t')->nullable();
            $table->string('pengukuran_cos_r')->nullable();
            $table->string('pengukuran_cos_s')->nullable();
            $table->string('pengukuran_cos_t')->nullable();
            $table->string('pengukuran_akurasi')->nullable();
            $table->string('pengukuran_keterangan')->nullable();
            $table->string('pengukuran_foto')->nullable();
            $table->string('akhir_hasil_pemeriksaan')->nullable();
            $table->string('akhir_kesimpulan')->nullable();
            $table->string('akhir_tindakan')->nullable();
            $table->string('akhir_barang_bukti')->nullable();
            $table->string('akhir_tanggal_penyelesaian')->nullable();
            $table->string('akhir_foto_barang_bukti')->nullable();
            $table->string('akhir_labor')->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('new_form_tidak_langsungs');
    }
};
