<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('new_form_langsungs', function (Blueprint $table) {
            $table->id();
            $table->foreignId('works_id')->constrained('work_orders')->onDelete('cascade')->onUpdate('cascade');
            $table->string('nama_saksi')->nullable();
            $table->string('alamat_saksi')->nullable();
            $table->string('nomor_identitas')->nullable();
            $table->string('pekerjaan')->nullable();
            $table->string('no_telpon_saksi')->nullable();
            $table->string('file_nomor_identitas')->nullable();
            $table->string('data_lama_merk')->nullable();
            $table->string('data_lama_no_reg')->nullable();
            $table->string('data_lama_no_seri')->nullable();
            $table->string('data_lama_tahun_pembuatan')->nullable();
            $table->string('data_lama_class')->nullable();
            $table->string('data_lama_konstanta')->nullable();
            $table->string('data_lama_rating_arus')->nullable();
            $table->string('data_lama_tegangan_nominal')->nullable();
            $table->string('data_lama_stand_kwh_meter')->nullable();
            $table->string('data_lama_jenis_pembatas')->nullable();
            $table->string('data_lama_alat_pembatas_merk')->nullable();
            $table->string('data_lama_rating_arus_2')->nullable();
            $table->string('data_lama_foto_kwh_meter')->nullable();
            $table->string('data_lama_foto_pembatas')->nullable();
            $table->string('data_baru_merk')->nullable();
            $table->string('data_baru_no_reg')->nullable();
            $table->string('data_baru_no_seri')->nullable();
            $table->string('data_baru_tahun_pembuatan')->nullable();
            $table->string('data_baru_class')->nullable();
            $table->string('data_baru_konstanta')->nullable();
            $table->string('data_baru_rating_arus')->nullable();
            $table->string('data_baru_tegangan_nominal')->nullable();
            $table->string('data_baru_stand_kwh_meter')->nullable();
            $table->string('data_baru_jenis_pembatas')->nullable();
            $table->string('data_baru_alat_pembatas_merk')->nullable();
            $table->string('data_baru_rating_arus_2')->nullable();
            $table->string('data_baru_foto_kwh_meter')->nullable();
            $table->string('data_baru_foto_pembatas')->nullable();
            $table->string('kwh_peralatan')->nullable();
            $table->string('kwh_segel')->nullable();
            $table->string('kwh_nomor_tahun_kode_segel')->nullable();
            $table->string('kwh_keterangan')->nullable();
            $table->string('kwh_foto_sebelum')->nullable();
            $table->string('kwh_post_peralatan')->nullable();
            $table->string('kwh_post_segel')->nullable();
            $table->string('kwh_post_nomor_tahun_kode_segel')->nullable();
            $table->string('kwh_foto_sesudah')->nullable();
            $table->string('terminal_peralatan')->nullable();
            $table->string('terminal_segel')->nullable();
            $table->string('terminal_nomor_tahun_kode_segel')->nullable();
            $table->string('terminal_keterangan')->nullable();
            $table->string('terminal_foto_sebelum')->nullable();
            $table->string('terminal_post_peralatan')->nullable();
            $table->string('terminal_post_segel')->nullable();
            $table->string('terminal_post_nomor_tahun_kode_segel')->nullable();
            $table->string('terminal_foto_sesudah')->nullable();
            $table->string('pelindung_kwh_peralatan')->nullable();
            $table->string('pelindung_kwh_segel')->nullable();
            $table->string('pelindung_kwh_nomor_tahun_kode_segel')->nullable();
            $table->string('pelindung_kwh_keterangan')->nullable();
            $table->string('pelindung_kwh_foto_sebelum')->nullable();
            $table->string('pelindung_kwh_post_peralatan')->nullable();
            $table->string('pelindung_kwh_post_segel')->nullable();
            $table->string('pelindung_kwh_post_nomor_tahun_kode_segel')->nullable();
            $table->string('pelindung_kwh_foto_sesudah')->nullable();
            $table->string('busbar_peralatan')->nullable();
            $table->string('busbar_segel')->nullable();
            $table->string('busbar_nomor_tahun_kode_segel')->nullable();
            $table->string('busbar_keterangan')->nullable();
            $table->string('busbar_foto_sebelum')->nullable();
            $table->string('busbar_post_peralatan')->nullable();
            $table->string('busbar_post_segel')->nullable();
            $table->string('busbar_post_nomor_tahun_kode_segel')->nullable();
            $table->string('busbar_foto_sesudah')->nullable();
            $table->string('papan_ok_peralatan')->nullable();
            $table->string('papan_ok_segel')->nullable();
            $table->string('papan_ok_nomor_tahun_kode_segel')->nullable();
            $table->string('papan_ok_keterangan')->nullable();
            $table->string('papan_ok_foto_sebelum')->nullable();
            $table->string('papan_ok_post_peralatan')->nullable();
            $table->string('papan_ok_post_segel')->nullable();
            $table->string('papan_ok_post_nomor_tahun_kode_segel')->nullable();
            $table->string('papan_ok_foto_sesudah')->nullable();
            $table->string('mcb_peralatan')->nullable();
            $table->string('mcb_segel')->nullable();
            $table->string('mcb_nomor_tahun_kode_segel')->nullable();
            $table->string('mcb_keterangan')->nullable();
            $table->string('mcb_foto_sebelum')->nullable();
            $table->string('mcb_post_peralatan')->nullable();
            $table->string('mcb_post_segel')->nullable();
            $table->string('mcb_post_nomor_tahun_kode_segel')->nullable();
            $table->string('mcb_foto_sesudah')->nullable();
            $table->string('pemeriksaan_keterangan')->nullable();
            $table->string('pemeriksaan_arus_1')->nullable();
            $table->string('pemeriksaan_arus_2')->nullable();
            $table->string('pemeriksaan_arus_3')->nullable();
            $table->string('pemeriksaan_arus_netral')->nullable();
            $table->string('pemeriksaan_voltase_netral_1')->nullable();
            $table->string('pemeriksaan_voltase_netral_2')->nullable();
            $table->string('pemeriksaan_voltase_netral_3')->nullable();
            $table->string('pemeriksaan_voltase_phase_1')->nullable();
            $table->string('pemeriksaan_voltase_phase_2')->nullable();
            $table->string('pemeriksaan_voltase_phase_3')->nullable();
            $table->string('pemeriksaan_cos_1')->nullable();
            $table->string('pemeriksaan_cos_2')->nullable();
            $table->string('pemeriksaan_cos_3')->nullable();
            $table->string('pemeriksaan_akurasi')->nullable();
            $table->string('pemeriksaan_foto_sebelum')->nullable();
            $table->string('wiring_terminal1')->nullable();
            $table->string('wiring_terminal2')->nullable();
            $table->string('wiring_terminal3')->nullable();
            $table->string('wiring_terminal4')->nullable();
            $table->string('wiring_terminal5')->nullable();
            $table->string('wiring_terminal6')->nullable();
            $table->string('wiring_terminal7')->nullable();
            $table->string('wiring_terminal8')->nullable();
            $table->string('wiring_terminal9')->nullable();
            $table->string('wiring_terminal11')->nullable();
            $table->string('wiring_keterangan_wiring_app')->nullable();
            $table->string('wiring_foto')->nullable();
            $table->string('akhir_hasil_pemeriksaan')->nullable();
            $table->string('akhir_kesimpulan')->nullable();
            $table->string('akhir_tindakan')->nullable();
            $table->string('akhir_barang_bukti')->nullable();
            $table->string('akhir_tanggal_penyelesaian')->nullable();
            $table->string('akhir_foto_barang_bukti')->nullable();
            $table->string('akhir_labor')->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('new_form_langsungs');
    }
};
